### ISSUE TITLE
HSL

### ISSUE THREAD

**Issue by sleighttt** [ToxxyTheTrash/SimplyDarkFuchsiaDarkness#3]
So glad this theme is back! This is one of my favorite themes. But is there a way to move HSL to the bottom instead of the top?

**Comment by ToxxyTheTrash** [comment]
you're just in luck!
gibbu does infact have his own addon for horizontal server list (which i do use).
to use it, in the original hsl file, add this line below the main import:
``@import url("https://gibbu.github.io/BetterDiscord-Themes/addons/bottomhsl.css");``

image for reference:
![image](https://user-images.githubusercontent.com/28952722/101993614-3d022100-3cbc-11eb-903f-251cbd5e44c7.png)

**Comment by sleighttt** [comment]
Thanks!
