### ISSUE TITLE
it borke

### ISSUE THREAD

**Issue by kekkodance** [ToxxyTheTrash/SimplyDarkFuchsiaDarkness#5]
discord refactored 90% of classes in the client, ouch more dead code!

**Comment by ToxxyTheTrash** [comment]
all works fine on my end. you good?

**Comment by kekkodance** [comment]
nnot so much
![image](https://user-images.githubusercontent.com/53054786/148640009-0ade11cb-0d9c-4f62-98db-4361f9e59b61.png)
![image](https://user-images.githubusercontent.com/53054786/148640016-a64770f0-bbec-473e-8c24-2b3182f53ddf.png)
the change is on canary for now, but its coming on stable in a few days sooooo eh

**Comment by ToxxyTheTrash** [comment]
well kekko if you've read the readme, i test on stable, not ptb or canary. but thanks for reminding me of the impending doom that is discord's shitty decisions
